inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
